### ISSUE TITLE
Install error - vscode-dts/vscode.proposed.inlineCompletions.d.ts not found

### ISSUE THREAD

**Issue by sr57** [CodedotAl/code-clippy-vscode#14] opened 2022-06-27 20:54 UTC
npm install

```
...
From: https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.proposed.inlineCompletions.d.ts
Read more about proposed API at: https://code.visualstudio.com/api/advanced-topics/using-proposed-api
Failed to get https://raw.githubusercontent.com/microsoft/vscode/main/src/vscode-dts/vscode.proposed.inlineCompletions.d.ts
...
```

**Comment by codetin** [comment] 2022-07-20 03:38
![image](https://user-images.githubusercontent.com/203521/179891236-7112368a-2bd6-416b-a0a2-60400439a744.png)
now there are just another 2 file

**Comment by ncoop57** [comment] 2022-09-06 02:15
Please try now with the updated version that no longer requires VSCode insider and see if this error goes away

**Comment by SeeNoBee** [comment] 2023-03-24 11:00
Hello. I can confirm that the issue is still there.

**Comment by create-juicey-app** [comment] 2023-03-24 22:15
issue still here.

**Comment by ncoop57** [comment] 2023-07-01 18:21
Fixed in #1b1edf6ccbb2568cb1873459f53d63f5b6dbce2e

**Closed as completed by ncoop57** 2023-07-01 18:21 UTC
